### ISSUE TITLE
Général > Volet

### ISSUE THREAD

**Issue by JonathanetRaimond** [SocialGouv/carnet-de-bord#257]
- [x] Harmoniser l’animation de tous les volets avec glissement de la droite vers la gauche. Pour l’instant certains s’affichent en glissant depuis la droite et d’autres s’affichent d’un coup. #277
- [x] L’espacement entre le haut du volet et le contenu doit être de 100px. #250
- [x] L’espacement à gauche et à droite du contenu doit être de 50px. #250
- [x] Remplacer l’icône du btn permettant de fermer le volet. Elle doit être placée à 50px de haut de l’écran et 50px du bord droit (alignée avec le contenu) #250
- [x] Si il y a un btn « Mettre à jour » le texte de ce dernier doit être aligné avec le texte présent sous le titre
