### ISSUE TITLE
Fixes pour l'epic Admin

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#619]
- [x] rendre impossible à l'admin structure d'éditer le mail
- [x] repasser sur les pluriels
- [x] préciser Bénéficiaires SUIVIS
- [x] mettre à jour le fichier démo des bénéficiaires
- [x] vérifier le check Admin PDI sur le nombre de bénéfs sans structure

**Comment by Augustin82** [comment]
Done et push sur la PR principale.
