### ISSUE TITLE
Retours epic/admin

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#638]
- [x] ~~rediriger l'admin PDI vers sa home après l'onboarding~~
- [x] ~~donner l'accès aux hedgedoc en écriture à la team~~ pas possible sous ce format, réfléchir à une autre doc en ligne, ou à héberger les docs sur le site, avec une visu simple du markdown ?
- [x] problème d'espace et de pluriel sur l'admin pdi
- [x] problème de rafraîchissement de la liste des structures
- [x] gérer le pluriel de mes structures
- [x] bloquer la modif email
- [x] Envoyer un mail d'information au gestionnaire de structure lorsqu'on lui assigne une nouvelle structure
- [x] À faire à part : #639
- [x] Vérifier le model CSV "PDI Import bénéficiaires" car son import n'est pas accepté par le système
- [x] Problème lors de l'import d'un pro par Admin Structure quand le téléphone est mal formaté
- [x] ~~Ajouter une notice pour le model CSV "Gestionnaire de structure - Import liste de rattachement"~~ Pas nécessaire pour ce cas-là
- [x] Supprimer "Identifiant" du compte pro

N'hésitez pas à rajouter à la liste @ronanjames @lkouad @amaurydubot @JonathanRaimond pour vos retours sur la V0.
