### ISSUE TITLE
Epic - Récupération des données PE

### ISSUE THREAD

**Issue by Augustin82** [SocialGouv/carnet-de-bord#640]
- [ ] Mettre en place le système de récupération des fichiers : Phébus, FILr, NAS côté Fabrique, etc.
- [ ] Parser le fichier principal (données + suivi)
- [ ] Parser le fichier d'actions
- [ ] Réfléchir à quand et comment intégrer les données dans la DB, sous quelle forme
- [ ] Mettre en place la récupération et le parsing des données (cronjob, action k8s, etc.)
