### ISSUE TITLE
Créer un profil chargé d'orientation  - V0

### ISSUE THREAD

**Issue by lkouad** [SocialGouv/carnet-de-bord#732]
#### Problème:
Actuellement le diagnostic est réalisé par le référent et l’attribution du référent se fait par l’admin pdi. Dans la majorité des cas c’est le chargé d’orientation qui reçoit en premier le bénéficiaire et qui l’oriente vers une structure ou un référent sont évaluation de la situation.

#### Contexte Métier
"ETQ CO je reçoit le bénéficiaire pour réaliser un diagnostic de sa situation dès son entrée dans le dispositif RSA afin d’identifier le parcours le mieux adapté à sa situation et d’assure le relai auprès des différents référents insertion du département qui auront en charge le suivi du parcours d'insertion de la personne »

#### Parties prenantes et intérêts :
• Le Chargé d’orientation : il veut mettre à jour les informations du bénéficiaire, faire le diagnostic de la situation et l’orienter vers une structure ou un référent adapté
• Le référent : Il veut voir le diagnostic et les axes de travail proposé par le CO afin de valider l’orientation et prendre en charge la personne

#### Solutions:
Créer un profil CO pour permettre l'évaluation de la situation du bénéficiaire et son orientation
Le rattacher à un nom de structure plateforme d'orientation
Import des profils par l'admin PDI 

#### Onboarding:
Dépendance [ETQ Admin PDI]
j’importe une liste de chargé d’orientation

Parcours [ETQ Chargé d’orientation]
- [x] je reçois un courriel pour valider mon compte. J’ouvre le courriel et clique sur le bouton « Accéder à mon compte »
- [x] Le système redirige l’utilisateurs sur Carnet de bord et affiche un formulaire pour valider les informations personnelles de son compte._
- [x] Je vérifie mes infos et clique sur le bouton « Créer mon compte ».
- [x]  Le système enregistre la mise à jour des informations dans la base de données et affiche un message de confirmation._
Je clique sur le bouton « J’ai compris »
- [x] Le système redirige l’utilisateur sur la page « Orientation des bénéficiaires »_
- [x] Je suis connecté à mon compte.

![Capture d’écran 2022-06-10 à 11 53 06](https://user-images.githubusercontent.com/85908681/173040423-1b62cfcc-08fb-4491-a24e-b81f08c93b1b.png)

V0
- [x]  Le CO peut élaborer le diagnostic de situation,
- [x] Le CO peut rattacher des accompagnateurs au groupe de suivi (non référent exemple Assistante social)
- [x] Le CO peut proposer une orientation adapter à son responsable en sélectionnant un Type d’accompagnement : Social, Professionnel ou Socio-professionnel
![form-orientation-CO](https://user-images.githubusercontent.com/85908681/162794049-a38ed32c-e6ca-4f3a-8b48-bbb76611ba78.png)

![bloc-sociopro](https://user-images.githubusercontent.com/85908681/162794119-b95efd87-5c2a-4080-953a-982697424305.png)

- [x] Le CO peut procéder à l’orientation vers le référent unique en sélectionnant une structure et un référent depuis le tableau d'orientation.
![Tableau_orientation](https://user-images.githubusercontent.com/85908681/162794747-36abb564-3810-461e-98b2-5aff51f732a7.png)

- [x] Le CO peut mettre une date de début et date de fin du CER ou du CEO (contrat d’engagement et d’orientation)
![Type-contrat](https://user-images.githubusercontent.com/85908681/163011018-226e29f2-9037-4578-ad9f-d7273f2b258e.png)

![Ajouter-axe-de-travail](https://user-images.githubusercontent.com/85908681/162795099-be71febe-a97b-4396-9b14-c90ead909a77.png)

Maquette :
https://www.figma.com/file/Y3PjnOSgwjRlNYMyv71TvB/MAQ-CHARGE-ORIENTATION-V0?node-id=0%3A1

  ####Documentation
  [Parcours Orientation/Réorientatio, #609](https://github.com/SocialGouv/carnet-de-bord/discussions/609) (comment)
####Out scope
le rattachement à une structure en V0 lui associer "plateforme d'orientatio
